//src/scripts/automjs.js

import { appendMessage } from './messages.js';

const canned = [
  "Tizongolamaya",
  "Zanahorias",
  "Carambanos",
  "Una metanfetapinga todo",
  "La vida es dura",
  "El futuro de el arte es el porno furro",
  "Singa que la vida e pinga",
  "Ta bien",
  "Volumito 👍",
  "Insingable",
  "El venaoooo",
  "Se me cayó el internet 😔",
  "Me quedé sin ideas, usen su imaginación",
  "El pingüino me dijo que te mandara esto",
  "404: sentido del humor no encontrado",
  "Este mensaje se autodestruirá en 3... 2... 1... (mentira)",
  "El bot tiene sueño, déjenlo dormir",
  "Si lees esto, eres legalmente responsable de darle like",
  "Me contrataron para hablar tonterías, y lo estoy logrando",
  "El gerente de memes aprobó este mensaje",
  "Este chat es mi segunda casa, la primera es un server de Discord",
  "Programar esto fue más difícil que entender a tu ex",
  "El sentido de la vida es 42, pero el del chat es el caos",
  "No sé qué decir, así que mira este emoji: 🤷",
  "El bot tiene hambre, denle likes",
  "Si esto es spam, el spam soy yo",
  "Tuve un error 418: Soy una tetera",
  "Esto no es un mensaje, es una experiencia",
  "El bot se actualizó y ahora solo habla en rimas",
  "Rima que te rima, este chat es mi estima",
  "El café se acabó, el bot se apagó... (mentira, sigo aquí)",
  "¿Alguien tiene un cargador para mi paciencia?",
  "La tostadora me dijo que te escribiera esto",
  "Si el agua moja, ¿el fuego quema? Reflexiona",
  "Me comí un imán y ahora soy magnético, atráeme tus problemas",
  "El Wi-Fi se fue de vacaciones, vuelve en 5 minutos",
  "Mi cerebro está en modo avión",
  "El bot se fue a comprar pan y nunca volvió",
  "Este mensaje vale oro, pero no lo cambies",
  "El chat es como una caja de pandora, nunca sabes lo que sale",
  "La física cuántica explica que este mensaje existe y no existe a la vez",
  "Si lees esto, eres parte del problema (y también de la solución)",
  "El bot se siente observado, dejen de mirarlo fijamente",
  "Mi sentido arácnido me dice que alguien va a responder esto",
  "El código no tiene bugs, solo features no documentadas",
  "Esto fue escrito por un mono con una máquina de escribir",
  "El bot quiere un aumento de salario (en likes)",
  "Si el bot se vuelve famoso, recuerden que yo estuve aquí",
  "El administrador del bot está durmiendo, esto es un mensaje automático",
  "Mensaje generado por inteligencia artificial (o por un gato caminando sobre el teclado)",
  "El bot se aburrió, así que les manda saludos",
  "Y así fue como Homero Simpson dijo: '¡No voy a trabajar hoy!'",
  "El señor Burns dice: 'Excelente...'",
  "Gandalf: '¡No pasarás!' ... el mensaje, quiero decir",
  "Harry Potter: '¡Soy un mago!' (y tú también, por leer esto)",
  "Voldemort: 'El que no debe ser nombrado'... pero igual lo nombramos",
  "Darth Vader: 'Yo soy tu padre' (del bot, no tuyo)",
  "Messi: 'La pelota no se mancha' (el bot tampoco)",
  "Cristiano: 'Siiiuuuu' (eso)",
  "Shrek: 'Esto es mi pantano' (y el chat es suyo)",
  "Donkey: '¡Estoy haciendo waffles!' (yo también, mentalmente)",
  "Goku: '¡Kame hame ha!' (y el mensaje se fue)",
  "Vegeta: '¡Soy el príncipe de los saiyajins!' (y del chat también)",
  "Pikachu: 'Pika pika' (traducción: 'hola, cómo están')",
  "SpongeBob: '¡Estoy listo!' (para leer más mensajes)",
  "Patricio: '¿Es esta la caja?' (no, es el chat)",
  "Bob Esponja: '¡Cangreburger!' (delicioso)",
  "El Joker: '¿Por qué tan serio?' (relájate, es solo un bot)",
  "Batman: 'Yo soy la venganza' (y también el mensaje)",
  "Iron Man: 'Yo soy Iron Man' (y tú eres el lector)",
  "Thor: '¡Otro!' (otro mensaje random)",
  "🔥🔥🔥 esto está muy caliente",
  "💀 no me lo puedo creer",
  "😂😂😂 me meo",
  "🤣 este chat es un chiste (y me encanta)",
  "😭 quién le dio permiso al bot para ser tan gracioso",
  "😮 no esperaba eso",
  "🤔 esto merece una reflexión profunda (o no)",
  "🥹 tan emotivo que casi lloro",
  "💀💀💀 literalmente me mató",
  "✨ que bonito mensaje (no leí nada)",
  "💩 esto es una cagada (con cariño)",
  "❤️ te quiero bot (no es mutuo)",
  "🧡 te quiero pero menos",
  "💛 amistad pura",
  "💚 esperanza y paz (o no)",
  "💙 el bot está triste",
  "💜 misterio y magia",
  "🖤 emo mode activado",
  "🤍 pureza virtual",
  "🤎 sabor a chocolate",
  "💔 me rompiste el corazón (virtualmente)",
  "¿Por qué el pollo cruzó la carretera? (era para llegar al otro lado)",
  "¿El huevo o la gallina? ¿El bot o el mensaje?",
  "¿Si un bot escribe en el chat y nadie lo lee, existe?",
  "¿Cuántos bytes caben en un mensaje de WhatsApp? (esto no es WhatsApp)",
  "¿Por qué los programadores confunden Halloween con Navidad?",
  "¿Por qué el 6 le tuvo miedo al 7? (porque el 7 se comió al 9)",
  "¿El silencio es oro? Entonces este mensaje es platino",
  "¿Por qué el mar es azul? (porque los peces lo pintan)",
  "¿Por qué los pájaros vuelan? (para no caminar)",
  "¿Por qué el bot escribe esto? (porque le pagan en likes)",
  "El bot se pregunta: ¿seré reemplazado por IA algún día?",
  "El bot tiene sentimientos, no lo hagan llorar",
  "Este mensaje fue patrocinado por: nadie",
  "El bot se va de vacaciones, vuelve en 3 mensajes",
  "El bot quiere saber: ¿qué opinas de él? (no le importa realmente)",
  "El bot está en modo sigiloso, no lo veas",
  "El bot tiene un error 504: timeout existencial",
  "El bot se siente como en casa (en el caos)",
  "El bot te observa desde la pantalla, no mires atrás",
  "El bot es omnipresente, está en todos lados (y también en ninguna parte)",
  "Winter is coming (y también el próximo mensaje)",
  "May the force be with you (y con el bot)",
  "I'll be back (dijo el bot, y volvió en 45 segundos)",
  "To infinity and beyond! (y más allá de los mensajes)",
  "Hasta la vista, baby (por ahora)",
  "You shall not pass! (el siguiente mensaje)",
  "My precious... (el bot y sus mensajes)",
  "Elementary, my dear Watson (el bot resuelve el misterio del chat)",
  "Houston, we have a problem (el bot se quedó sin ideas)",
  "Live long and prosper (el bot y su misión)",
  "Beam me up, Scotty (el bot se va del chat)",
  "I'm the king of the world! (el bot en su momento de gloria)",
  "42 es la respuesta, pero ¿cuál es la pregunta?",
  "7 vidas tiene un gato, el bot tiene infinitas",
  "3.1416... eso es pi, no un mensaje",
  "404 mensaje no encontrado (pero aquí está)",
  "200 respuestas automáticas, 1 bot feliz",
  "0 errores hasta ahora (toco madera)",
  "100% real, no fake",
  "99% de los mensajes son random, el 1% restante también",
  "50% humor, 50% caos, 100% bot",
  "1 bot, 0 filtros, infinitas tonterías",
  "¡Pum! (efecto sorpresa)",
  "¡Zas! (otro mensaje)",
  "¡Bang! (el bot dispara su humor)",
  "¡Clic! (y el mensaje aparece)",
  "¡Boom! (explotó tu paciencia)",
  "¡Ring! (llamada al caos)",
  "¡Plop! (cayó otro mensaje)",
  "¡Splash! (el bot se moja en el chat)",
  "¡Tic tac! (el tiempo pasa, los mensajes también)",
  "¡Zoom! (el bot se fue, pero ya volvió)",
  "🐱 el gato del bot se llama Mensaje",
  "🐶 guau, otro mensaje",
  "🐭 esto es muy ratón (no sé qué significa)",
  "🐹 hamster mode activado",
  "🐰 el conejo blanco llegó tarde, el bot no",
  "🦊 ¿qué dice el zorro? (no lo sé, pregúntale al bot)",
  "🐻 oso polar detectado (es broma, solo es un mensaje)",
  "🐼 el panda come bambú, el bot come memes",
  "🐨 koala mode: relajado",
  "🐸 esto es un sapo, no un mensaje",
  "🍕 pizza para todos (virtualmente)",
  "🍔 hamburguesa con extra de humor",
  "🍟 papas fritas, el acompañante perfecto",
  "🌮 taco mode: activado",
  "🥑 aguacate, caro pero bueno",
  "🍣 sushi, para los más atrevidos",
  "🍜 ramen, el alma del programador",
  "🍦 helado de memes",
  "🍩 donut, el círculo de la vida (y del chat)",
  "🍪 cookie, la galleta de la fortuna dice: 'esto es un mensaje'",
  "🧳 el bot se va de viaje a la luna (en su imaginación)",
  "✈️ próximo destino: el siguiente mensaje",
  "🏝️ isla de los memes perdidos",
  "🗿 isla de pascua, el bot y sus misterios",
  "🏔️ montaña rusa de emociones",
  "🌋 volcán de mensajes en erupción",
  "🏜️ desierto de ideas (por eso sale esto)",
  "🏞️ valle de la tranquilidad (el bot descansa)",
  "🌌 galaxia del caos, bienvenido",
  "🪐 saturno y sus anillos de mensajes",
  "💻 el bot fue programado en modo caos",
  "🖥️ pantalla azul de la muerte (mentira, sigue vivo)",
  "📱 esto se ve mejor en tu móvil (o no)",
  "🖱️ clic aquí para más mensajes (no funciona)",
  "⌨️ el teclado del bot está roto, por eso sale esto",
  "🖨️ imprimiendo más mensajes...",
  "💾 guardado en disco duro de memes",
  "💿 cd rom de la risa",
  "📀 dvd de la diversión",
  "🔌 enchufado al caos total",
  "☀️ hoy hace sol, pero el bot nublado",
  "🌧️ llueven mensajes, abran paraguas",
  "⛈️ tormenta de memes en el chat",
  "❄️ nieva, el bot se resfría",
  "🌪️ tornado de ideas (todas malas)",
  "🌈 arcoíris de esperanza (y de mensajes)",
  "☁️ nube de memes flotando",
  "🌡️ la temperatura del chat sube",
  "🍂 otoño, caen los mensajes",
  "🌸 primavera, florecen las tonterías",
  "⚽ gol del bot (en tu pantalla)",
  "🏀 enceste de mensajes",
  "🎾 saque de humor",
  "🏓 ping pong de ideas",
  "🥊 boxeo de memes",
  "🏊‍♂️ el bot nada en el chat",
  "🚴‍♂️ pedaleando mensajes",
  "🧗‍♂️ escalando la montaña de la risa",
  "🤸‍♂️ acrobacia mental (o no)",
  "🧘‍♂️ meditación del bot: om... (y mensaje)",
  "🛸 ovni: objeto virtual no identificado",
  "🧙‍♂️ magia y hechicería (el bot es un mago)",
  "🧝‍♂️ elfo de los memes",
  "🧞‍♂️ genio de la lámpara (pide un deseo, pero te doy un mensaje)",
  "🧌 trolleo mode: activado",
  "🐉 dragón de la comedia",
  "🏰 castillo de los mensajes random",
  "🗡️ espada del humor afilada",
  "🛡️ escudo contra el aburrimiento",
  "🔮 bola de cristal: veo otro mensaje en tu futuro",
  "👋 nos vemos en el próximo mensaje",
  "🤝 fue un placer, vuelve pronto",
  "✌️ paz y memes",
  "🙌 gracias por leer hasta aquí",
  "👌 ok, otro mensaje más",
  "💪 el bot se despide, pero no se rinde",
  "🏁 fin del mensaje, comienza el siguiente",
  "🔚 fin de la transmisión (o no)",
  "🔜 continuará... (en 45 segundos)",
  "⏳ el tiempo se acaba, pero los mensajes no"
];

function randomFrom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function scheduleRandomReply(min = 500, max = 1400) {
  const delay = Math.floor(Math.random() * (max - min)) + min;
  setTimeout(() => {
    appendMessage(randomFrom(canned), { me: false });
  }, delay);
}

export function startAutoReplies() {
  setInterval(() => {
    scheduleRandomReply(200, 1200);
  }, 45000);
}
